# /etc/netplan/50-cloud-init.yaml
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: false
            addresses: [192.168.4.121/24]
            gateway4: 192.168.4.1
            nameservers:
                addresses: [8.8.8.8, 1.1.1.1]
